### ISSUE TITLE
Investigate reports of TypeScript SDK showing multiple rows with the same primary key after a reducer which does a PK-ful update.

### ISSUE THREAD

**Issue by bfops** [clockworklabs/spacetimedb-typescript-sdk#120]
[Dynny on the public discord reports](https://discord.com/channels/1037340874172014652/1138987509834059867/1272574420258390148):

In the TypeScript SDK on Firefox, a `SomeTable.filterByNonUniqueColumn` is returning multiple rows with the same primary key value.

[The module is built in C#, and is performing a PK-ful update.](https://github.com/PoglyApp/pogly-standalone/blob/2ee32df648bac76491b19263218318d16a17b890/server/Elements/ElementReducers.cs#L593)

The client is built in TypeScript, and in the report is running on Firefox. [The client is subscribed to all rows of the table in question](https://github.com/PoglyApp/pogly-standalone/blob/0.1.1-release/src/Utility/SetSubscriptions.ts), and is reportedly seeing the duplicate in [a `filterByLayoutId` call in the client](https://github.com/PoglyApp/pogly-standalone/blob/1be69ba254bd888e8ec675552f0eb6e92f97ab5c/src/StDB/Hooks/useFetchElements.tsx#L37), where `layout_id` is a non-unique column.

Reportedly, the user has tested in Google Chrome and not seen the issue.

**Comment by PuruVJ** [comment]
This has been resolved and released long time ago in 0.12
